### ISSUE TITLE
Add JSXText, JSXFragment, JSXEmptyExpression

### ISSUE THREAD

**Issue by barelyhuman** [Qard/astring-jsx#8]
Thanks for your work on this project! 👍🏼 

We seem to be missing `JSXText` and `JSXFragment` helpers, which is what the diff below adds, let me know if you'd want to go ahead with a PR?

```diff
diff --git a/node_modules/astring-jsx/index.js b/node_modules/astring-jsx/index.js
index 809b217..b058268 100644
--- a/node_modules/astring-jsx/index.js
+++ b/node_modules/astring-jsx/index.js
@@ -54,6 +54,10 @@ var generator = Object.assign({
     output.write('=');
     this[node.value.type](node.value, state);
   },
+  JSXText: function JSXText(node,state){
+    var output = state.output;
+    output.write(node.value);
+  },
   // namespaced:attr="something"
   JSXNamespacedName: function JSXNamespacedName(node, state) {
     var output = state.output;
@@ -65,9 +69,21 @@ var generator = Object.assign({
   JSXExpressionContainer: function JSXExpressionContainer(node, state) {
     var output = state.output;
     output.write('{');
+    console.log({node});
     this[node.expression.type](node.expression, state);
     output.write('}');
   },
+  JSXEmptyExpression: function JSXEmptyExpression(node,state){
+    // do nothing
+  },
+  JSXFragment: function JSXFragment(node, state) {
+    var output = state.output
+    output.write("<>")
+    for (child of node.children){
+      this[child.type](child,state)
+    }
+    output.write("</>")
+  },
 }, astring.defaultGenerator);
 
 function astringJsx (ast, options) {
```

**Comment by eliot-akira** [comment]
It looks like this project is no longer maintained. Thank you for the above code, it was useful for something I'm working on. In addition, this snippet for `JSXFragment` from another issue might be good to include.

```js
JSXFragment: function JSXFragment(node, state) {
  state.write('<>')
  for (const child of node.children) {
    this[child.type](child, state)
  }
  state.write('</>')
}
```

Maybe someone can fork this project and publish a new package to NPM?

**Comment by barelyhuman** [comment]
Oh, I might have missed the patch file update which has this, thanks , it's already a part of 
https://github.com/barelyhuman/preact-island-plugins/blob/main/lib/astring.js

> Maybe someone can fork this project and publish a new package to NPM?

I could do that, though, i'm not sure how helpful that would be since it'd still be inside an issue so people might not find it as quickly

**Comment by barelyhuman** [comment]
Ah, nevermind, 
Let's do this 

https://github.com/barelyhuman/astring-jsx
https://www.npmjs.com/package/@barelyhuman/astring-jsx

**Comment by eliot-akira** [comment]
Great, thank you!
